PETSC_DIR=/lus/grand/projects/ATPESC2021/usr/MathPackages/spack/opt/spack/linux-rhel7-haswell/gcc-8.2.0/petsc-3.15.2-mavfks5tndii2j4dyoa27434utwo7lel

CFLAGS		 =
FFLAGS		 =
CPPFLAGS         =
FPPFLAGS         =
EXAMPLESC        = multidim_rosenbrock.c
EXAMPLESF        = 
EXAMPLESCH       =
EXAMPLESFH       = 
LOCDIR		 = 
MANSEC		 =
DOCS		 =
DIRS		 =
CLEANFILES   = multidim_rosenbrock

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
